#!/bin/sh

echo "// do not edit this file - edit sender.txt and run create_sender_javascript.sh" > sender.js
echo "var stationArray = new Array (" >> sender.js
cat sender.txt | awk -F, '{ printf "new Station(\"%s\",\"%s\",\"%s\",\"%s\"),\n",$1,$2,$3,$4}' | sort >> sender.js
echo "new Station(\"\", \"\", \"\", \"\"));" >> sender.js

